'use client'

import { Link } from '@tanstack/react-router'
import {
  AlertCircle,
  ArrowLeft,
  CheckCircle2,
  Clock,
  ExternalLink,
  FileQuestion,
  Loader2,
  Terminal,
  TestTube2,
  XCircle,
} from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { useTask } from '@/features/tasks/hooks/use-task'
import { useQARun } from '@/features/tasks/hooks/use-qa-run'
import type { QaRunStatus } from '@/features/tasks/types'
import { cn } from '@/lib/utils'
import { ApiClientError } from '@/lib/api-client'

const STATUS_META: Record<QaRunStatus, { label: string; variant: 'secondary' | 'warning' | 'success' | 'destructive' | 'outline'; icon: typeof Clock }> = {
  queued: { label: 'Queued', variant: 'secondary', icon: Clock },
  running: { label: 'Running', variant: 'warning', icon: Loader2 },
  passed: { label: 'Passed', variant: 'success', icon: CheckCircle2 },
  failed: { label: 'Failed', variant: 'destructive', icon: XCircle },
  canceled: { label: 'Canceled', variant: 'outline', icon: XCircle },
}

export function QARunDetail({ runId }: { runId: string }) {
  const { data: run, isLoading, error } = useQARun(runId)
  const { data: task } = useTask(run?.task_id ?? '')

  if (isLoading) {
    return <QARunDetailSkeleton />
  }

  if (error instanceof ApiClientError && error.statusCode === 404) {
    return <NotFoundState runId={runId} />
  }

  if (error) {
    return <ErrorState error={error} />
  }

  if (!run) {
    return <NotFoundState runId={runId} />
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="space-y-1">
          <nav className="flex items-center gap-1 text-sm text-muted-foreground">
            <Link to="/qa" className="hover:text-foreground">
              QA
            </Link>
            <span>/</span>
            <span className="font-medium text-foreground">{run.id.slice(0, 8)}</span>
          </nav>
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
              <TestTube2 className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h1 className="text-xl font-semibold tracking-tight">QA Run</h1>
              {task ? (
                <p className="text-sm text-muted-foreground">{task.title}</p>
              ) : (
                <p className="text-sm text-muted-foreground">{run.task_id}</p>
              )}
            </div>
          </div>
        </div>

        <Button variant="outline" size="sm" asChild>
          <Link to="/qa">
            <ArrowLeft className="h-4 w-4" />
            Back to QA
          </Link>
        </Button>
      </div>

      <div className="grid gap-4 lg:grid-cols-[1fr_340px]">
        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex flex-wrap items-center gap-2 text-lg">
                <QaStatusBadge status={run.status} />
                {run.exit_code !== null ? (
                  <Badge variant="outline">exit {run.exit_code}</Badge>
                ) : null}
              </CardTitle>
              <CardDescription>
                {formatDate(run.started_at ?? run.created_at)}
                {run.completed_at ? ` -> ${formatDate(run.completed_at)}` : ''}
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              <KeyValue label="Target URL" value={run.target_url} />
              <KeyValue label="Command" value={run.test_command} mono />
            </CardContent>
          </Card>

          <LogPanel title="stdout" value={run.stdout} />
          <LogPanel title="stderr" value={run.stderr} tone="danger" />
        </div>

        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Artifacts</CardTitle>
              <CardDescription>Paths generated by the QA command.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              <Artifact label="Playwright report" value={run.report_path} />
              <Artifact label="Test results" value={run.trace_path} />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Task</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <KeyValue label="Task ID" value={run.task_id} mono />
              {task ? (
                <Button variant="outline" size="sm" asChild>
                  <Link to="/board">
                    <ExternalLink className="h-4 w-4" />
                    Open on board
                  </Link>
                </Button>
              ) : null}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

function QaStatusBadge({ status }: { status: QaRunStatus }) {
  const meta = STATUS_META[status]
  const Icon = meta.icon
  return (
    <Badge variant={meta.variant} className="gap-1">
      <Icon className={cn('h-3 w-3', status === 'running' && 'animate-spin')} />
      {meta.label}
    </Badge>
  )
}

function KeyValue({ label, value, mono }: { label: string; value?: string | null; mono?: boolean }) {
  return (
    <div className="min-w-0 space-y-1">
      <div className="text-xs font-medium uppercase text-muted-foreground">{label}</div>
      <div
        className={cn(
          'break-all rounded-md border bg-muted/20 px-3 py-2 text-sm',
          mono && 'font-mono text-xs'
        )}
      >
        {value || 'None'}
      </div>
    </div>
  )
}

function Artifact({ label, value }: { label: string; value?: string | null }) {
  return (
    <div className="flex items-start justify-between gap-3 rounded-md border bg-muted/20 px-3 py-2">
      <div className="min-w-0">
        <div className="text-sm font-medium">{label}</div>
        <div className="break-all font-mono text-xs text-muted-foreground">{value || 'Not found'}</div>
      </div>
      {value ? <Badge variant="outline">saved</Badge> : <Badge variant="secondary">none</Badge>}
    </div>
  )
}

function LogPanel({
  title,
  value,
  tone = 'default',
}: {
  title: string
  value?: string | null
  tone?: 'default' | 'danger'
}) {
  return (
    <Card>
      <CardHeader className="py-4">
        <CardTitle className="flex items-center gap-2 text-lg">
          <Terminal className="h-5 w-5" />
          {title}
        </CardTitle>
      </CardHeader>
      <CardContent>
        {value ? (
          <pre
            className={cn(
              'max-h-[520px] overflow-auto whitespace-pre-wrap rounded-md border bg-background p-4 font-mono text-xs leading-relaxed',
              tone === 'danger' ? 'text-foreground' : 'text-muted-foreground'
            )}
          >
            {value}
          </pre>
        ) : (
          <div className="flex h-24 items-center justify-center rounded-md border border-dashed text-sm text-muted-foreground">
            No output
          </div>
        )}
      </CardContent>
    </Card>
  )
}

function QARunDetailSkeleton() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="space-y-2">
          <Skeleton className="h-4 w-36" />
          <Skeleton className="h-8 w-56" />
        </div>
        <Skeleton className="h-8 w-28" />
      </div>
      <div className="grid gap-4 lg:grid-cols-[1fr_340px]">
        <div className="space-y-4">
          <Skeleton className="h-56 w-full" />
          <Skeleton className="h-72 w-full" />
        </div>
        <Skeleton className="h-56 w-full" />
      </div>
    </div>
  )
}

function NotFoundState({ runId }: { runId: string }) {
  return (
    <Card>
      <CardContent className="flex flex-col items-center justify-center py-16">
        <FileQuestion className="mb-4 h-12 w-12 text-muted-foreground" />
        <h2 className="mb-2 text-xl font-semibold">QA Run Not Found</h2>
        <p className="mb-6 max-w-md text-center text-muted-foreground">
          The QA run with ID &quot;{runId}&quot; could not be found.
        </p>
        <Button asChild>
          <Link to="/qa">Back to QA</Link>
        </Button>
      </CardContent>
    </Card>
  )
}

function ErrorState({ error }: { error: Error }) {
  return (
    <Card>
      <CardContent className="flex flex-col items-center justify-center py-16">
        <AlertCircle className="mb-4 h-12 w-12 text-destructive" />
        <h2 className="mb-2 text-xl font-semibold">Error Loading QA Run</h2>
        <p className="mb-2 max-w-md text-center text-muted-foreground">
          There was a problem loading the QA run.
        </p>
        <p className="mb-6 font-mono text-sm text-destructive">{error.message}</p>
        <Button variant="outline" onClick={() => window.location.reload()}>
          Try Again
        </Button>
      </CardContent>
    </Card>
  )
}

function formatDate(value: string) {
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return value
  }
  return date.toLocaleString()
}
